// Generated by CoffeeScript 1.7.1
(function() {
  var Q, call_api, config, https, only, querystring, transformation_string, utils, _,
    __slice = [].slice;

  _ = require("lodash");

  https = require('https');

  utils = require("./utils");

  config = require("./config");

  querystring = require("querystring");

  Q = require('q');

  exports.ping = function(callback, options) {
    if (options == null) {
      options = {};
    }
    return call_api("get", ["ping"], {}, callback, options);
  };

  exports.usage = function(callback, options) {
    if (options == null) {
      options = {};
    }
    return call_api("get", ["usage"], {}, callback, options);
  };

  exports.resource_types = function(callback, options) {
    if (options == null) {
      options = {};
    }
    return call_api("get", ["resources"], {}, callback, options);
  };

  exports.resources = function(callback, options) {
    var resource_type, type, uri, _ref;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = options["type"];
    uri = ["resources", resource_type];
    if (type != null) {
      uri.push(type);
    }
    if ((options.start_at != null) && Object.prototype.toString.call(options.start_at) === '[object Date]') {
      options.start_at = options.start_at.toUTCString();
    }
    return call_api("get", uri, only(options, "next_cursor", "max_results", "prefix", "tags", "context", "direction", "moderations", "start_at"), callback, options);
  };

  exports.resources_by_tag = function(tag, callback, options) {
    var resource_type, uri, _ref;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    uri = ["resources", resource_type, "tags", tag];
    return call_api("get", uri, only(options, "next_cursor", "max_results", "tags", "context", "direction", "moderations"), callback, options);
  };

  exports.resources_by_moderation = function(kind, status, callback, options) {
    var resource_type, uri, _ref;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    uri = ["resources", resource_type, "moderations", kind, status];
    return call_api("get", uri, only(options, "next_cursor", "max_results", "tags", "context", "direction", "moderations"), callback, options);
  };

  exports.resources_by_ids = function(public_ids, callback, options) {
    var params, resource_type, type, uri, _ref, _ref1;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = (_ref1 = options["type"]) != null ? _ref1 : "upload";
    uri = ["resources", resource_type, type];
    params = only(options, "tags", "context", "moderations");
    params["public_ids[]"] = public_ids;
    return call_api("get", uri, params, callback, options);
  };

  exports.resource = function(public_id, callback, options) {
    var resource_type, type, uri, _ref, _ref1;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = (_ref1 = options["type"]) != null ? _ref1 : "upload";
    uri = ["resources", resource_type, type, public_id];
    return call_api("get", uri, only(options, "exif", "colors", "faces", "image_metadata", "pages", "phash", "coordinates", "max_results"), callback, options);
  };

  exports.update = function(public_id, callback, options) {
    var params, resource_type, type, uri, _ref, _ref1;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = (_ref1 = options["type"]) != null ? _ref1 : "upload";
    uri = ["resources", resource_type, type, public_id];
    params = utils.updateable_resource_params(options);
    if (options.moderation_status != null) {
      params.moderation_status = options.moderation_status;
    }
    return call_api("post", uri, params, callback, options);
  };

  exports.delete_resources = function(public_ids, callback, options) {
    var resource_type, type, uri, _ref, _ref1;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = (_ref1 = options["type"]) != null ? _ref1 : "upload";
    uri = ["resources", resource_type, type];
    return call_api("delete", uri, _.extend({
      "public_ids[]": public_ids
    }, only(options, "keep_original", "invalidate")), callback, options);
  };

  exports.delete_resources_by_prefix = function(prefix, callback, options) {
    var resource_type, type, uri, _ref, _ref1;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = (_ref1 = options["type"]) != null ? _ref1 : "upload";
    uri = ["resources", resource_type, type];
    return call_api("delete", uri, _.extend({
      prefix: prefix
    }, only(options, "keep_original", "next_cursor", "invalidate")), callback, options);
  };

  exports.delete_resources_by_tag = function(tag, callback, options) {
    var resource_type, uri, _ref;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    uri = ["resources", resource_type, "tags", tag];
    return call_api("delete", uri, only(options, "keep_original", "next_cursor", "invalidate"), callback, options);
  };

  exports.delete_all_resources = function(callback, options) {
    var resource_type, type, uri, _ref, _ref1;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    type = (_ref1 = options["type"]) != null ? _ref1 : "upload";
    uri = ["resources", resource_type, type];
    return call_api("delete", uri, _.extend({
      all: true
    }, only(options, "keep_original", "next_cursor", "invalidate")), callback, options);
  };

  exports.delete_derived_resources = function(derived_resource_ids, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["derived_resources"];
    return call_api("delete", uri, {
      "derived_resource_ids[]": derived_resource_ids
    }, callback, options);
  };

  exports.tags = function(callback, options) {
    var resource_type, uri, _ref;
    if (options == null) {
      options = {};
    }
    resource_type = (_ref = options["resource_type"]) != null ? _ref : "image";
    uri = ["tags", resource_type];
    return call_api("get", uri, only(options, "next_cursor", "max_results", "prefix"), callback, options);
  };

  exports.transformations = function(callback, options) {
    if (options == null) {
      options = {};
    }
    return call_api("get", ["transformations"], only(options, "next_cursor", "max_results"), callback, options);
  };

  exports.transformation = function(transformation, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["transformations", transformation_string(transformation)];
    return call_api("get", uri, only(options, "max_results"), callback, options);
  };

  exports.delete_transformation = function(transformation, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["transformations", transformation_string(transformation)];
    return call_api("delete", uri, {}, callback, options);
  };

  exports.update_transformation = function(transformation, updates, callback, options) {
    var params, uri;
    if (options == null) {
      options = {};
    }
    uri = ["transformations", transformation_string(transformation)];
    params = only(updates, "allowed_for_strict");
    if (updates.unsafe_update != null) {
      params.unsafe_update = transformation_string(updates.unsafe_update);
    }
    return call_api("put", uri, params, callback, options);
  };

  exports.create_transformation = function(name, definition, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["transformations", name];
    return call_api("post", uri, {
      transformation: transformation_string(definition)
    }, callback, options);
  };

  exports.upload_presets = function(callback, options) {
    if (options == null) {
      options = {};
    }
    return call_api("get", ["upload_presets"], only(options, "next_cursor", "max_results"), callback, options);
  };

  exports.upload_preset = function(name, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["upload_presets", name];
    return call_api("get", uri, only(options, "max_results"), callback, options);
  };

  exports.delete_upload_preset = function(name, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["upload_presets", name];
    return call_api("delete", uri, {}, callback, options);
  };

  exports.update_upload_preset = function(name, callback, options) {
    var params, uri;
    if (options == null) {
      options = {};
    }
    uri = ["upload_presets", name];
    params = utils.merge(utils.clear_blank(utils.build_upload_params(options)), only(options, "unsigned", "disallow_public_id"));
    return call_api("put", uri, params, callback, options);
  };

  exports.create_upload_preset = function(callback, options) {
    var params, uri;
    if (options == null) {
      options = {};
    }
    uri = ["upload_presets"];
    params = utils.merge(utils.clear_blank(utils.build_upload_params(options)), only(options, "name", "unsigned", "disallow_public_id"));
    return call_api("post", uri, params, callback, options);
  };

  exports.root_folders = function(callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["folders"];
    return call_api("get", uri, {}, callback, options);
  };

  exports.sub_folders = function(path, callback, options) {
    var uri;
    if (options == null) {
      options = {};
    }
    uri = ["folders", path];
    return call_api("get", uri, {}, callback, options);
  };

  exports.only = only = function() {
    var hash, key, keys, result, _i, _len;
    hash = arguments[0], keys = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    result = {};
    for (_i = 0, _len = keys.length; _i < _len; _i++) {
      key = keys[_i];
      if (hash[key] != null) {
        result[key] = hash[key];
      }
    }
    return result;
  };

  call_api = function(method, uri, params, callback, options) {
    var api_key, api_secret, api_url, cloud_name, cloudinary, deferred, handle_response, query_params, request, request_options, _ref, _ref1, _ref2, _ref3, _ref4, _ref5;
    deferred = Q.defer();
    cloudinary = (_ref = (_ref1 = options["upload_prefix"]) != null ? _ref1 : config().upload_prefix) != null ? _ref : "https://api.cloudinary.com";
    cloud_name = (function() {
      var _ref3;
      if ((_ref2 = (_ref3 = options["cloud_name"]) != null ? _ref3 : config().cloud_name) != null) {
        return _ref2;
      } else {
        throw "Must supply cloud_name";
      }
    })();
    api_key = (function() {
      var _ref4;
      if ((_ref3 = (_ref4 = options["api_key"]) != null ? _ref4 : config().api_key) != null) {
        return _ref3;
      } else {
        throw "Must supply api_key";
      }
    })();
    api_secret = (function() {
      var _ref5;
      if ((_ref4 = (_ref5 = options["api_secret"]) != null ? _ref5 : config().api_secret) != null) {
        return _ref4;
      } else {
        throw "Must supply api_secret";
      }
    })();
    api_url = [cloudinary, "v1_1", cloud_name].concat(uri).join("/");
    query_params = querystring.stringify(params);
    if (method === "get") {
      api_url += "?" + query_params;
    }
    request_options = require('url').parse(api_url);
    request_options = _.extend(request_options, {
      method: method.toUpperCase(),
      headers: {
        'Content-Type': 'application/x-www-form-urlencoded',
        'User-Agent': utils.USER_AGENT
      },
      auth: "" + api_key + ":" + api_secret
    });
    if (options.agent != null) {
      request_options.agent = options.agent;
    }
    handle_response = function(res) {
      var buffer, err_obj, error;
      if (_.includes([200, 400, 401, 403, 404, 409, 420, 500], res.statusCode)) {
        buffer = "";
        error = false;
        res.on("data", function(d) {
          return buffer += d;
        });
        res.on("end", function() {
          var e, result;
          if (error) {
            return;
          }
          try {
            result = JSON.parse(buffer);
          } catch (_error) {
            e = _error;
            result = {
              error: {
                message: "Server return invalid JSON response. Status Code " + res.statusCode
              }
            };
          }
          if (result["error"]) {
            result["error"]["http_code"] = res.statusCode;
          } else {
            result["rate_limit_allowed"] = parseInt(res.headers["x-featureratelimit-limit"]);
            result["rate_limit_reset_at"] = new Date(res.headers["x-featureratelimit-reset"]);
            result["rate_limit_remaining"] = parseInt(res.headers["x-featureratelimit-remaining"]);
          }
          if (result.error) {
            deferred.reject(result);
          } else {
            deferred.resolve(result);
          }
          if (callback != null) {
            return callback(result);
          }
        });
        return res.on("error", function(e) {
          var err_obj;
          error = true;
          err_obj = {
            error: {
              message: e,
              http_code: res.statusCode
            }
          };
          deferred.reject(err_obj.error);
          if (callback != null) {
            return callback(err_obj);
          }
        });
      } else {
        err_obj = {
          error: {
            message: "Server returned unexpected status code - " + res.statusCode,
            http_code: res.statusCode
          }
        };
        deferred.reject(err_obj.error);
        if (callback != null) {
          return callback(err_obj);
        }
      }
    };
    request = https.request(request_options, handle_response);
    request.on("error", function(e) {
      return callback({
        error: e
      });
    });
    request.setTimeout((_ref5 = options["timeout"]) != null ? _ref5 : 60);
    if (method !== "get") {
      request.write(query_params);
    }
    request.end();
    return deferred.promise;
  };

  transformation_string = function(transformation) {
    if (_.isString(transformation)) {
      return transformation;
    } else {
      return utils.generate_transformation_string(_.extend(transformation));
    }
  };

}).call(this);
